services:
  ffc-ffd-ahwr-stub:
    build:
      context: .
      target: production
    image: ffc-ffd-ahwr-stub
    container_name: ffc-ffd-ahwr-stub
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-ahwr-stub-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AUTH_HOST: ${AUTH_HOST:-http://ffc-ffd-proxy:3000}
      GATEWAY_HOST: ${GATEWAY_HOST:-http://localhost:3000}
      COOKIE_PASSWORD: the-password-must-be-at-least-32-characters-long
