# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ffd-ahwr-stub:
    build:
      target: development
    image: ffc-ffd-ahwr-stub-development
    container_name: ffc-ffd-ahwr-stub-development
    ports:
      - "4000:4000"
      - "9100:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
