environment: production
environmentCode:
name: ffc-ffd-ahwr-stub
namespace: ffc-ffd
workstream: ffc-ffd
image: ffc-ffd-ahwr-stub

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ffd-ahwr-stub-config-map

containerSecret:
  name: ffc-ffd-ahwr-stub-container-secret
  type: Opaque

deployment:
  priorityClassName: high

ingress:
  class: nginx
  endpoint: ffc-ffd-ahwr-stub
  server: example.com

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 4000
  authHost: ffc-ffd-auth

livenessProbe:
  path: /healthz
  port: 4000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 4000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
